const MONGOOSE_CONNECTION_STRING = process.env.MONGOOSE_CONNECTION_STRING;
const JWT_SECRET = process.env.JWT_SECRET;
const BALANCE_PRECISION = process.env.BALANCE_PRECISION;

module.exports = {
  MONGOOSE_CONNECTION_STRING,
  JWT_SECRET,
  BALANCE_PRECISION,
};
